### ISSUE TITLE
[Bug] Could not close window while loading image.

### ISSUE THREAD

**Issue by kuoruan** [nzbin/photoviewer#1]
I can't click the close button when the image is loading.

**Comment by nzbin** [comment]
@kuoruan It's not a bug, there has a layer div on top of modal when image is loading, you can customize the layer size as you like.

```css
.photoviewer-loader {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 2;
  text-align: center;
  color: #333;
}
```
